=== rafikatulhikmah0103/Pendidikan/tugasfika/bin/tugasfika/biodata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="logfika">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="mahasiswa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mahasiswa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="npm"/>
                <xs:element ref="nama"/>
                <xs:element ref="kelas"/>
                <xs:element ref="jurusan"/>
                <xs:element ref="biayasemester"/>
                <xs:element ref="kodekelas"/>
                <xs:element ref="asaldaerah"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="npm">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="kode" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama" type="xs:NCName"/>
    <xs:element name="kelas" type="xs:NMTOKEN"/>
    <xs:element name="jurusan" type="xs:string"/>
    <xs:element name="biayasemester">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">

    			<xs:minInclusive value="7000000"></xs:minInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="kodekelas">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">

    			<xs:minInclusive value="1"></xs:minInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="asaldaerah" type="xs:NCName"/>
</xs:schema>

=== rafikatulhikmah0103/Pendidikan/tugasfika/src/tugasfika/biodata.xml
<?xml version="1.0" encoding="UTF-8"?>
<logfika xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biodata.xsd">
<mahasiswa>
	<npm kode="00001">11540</npm>
	<nama>Rafika</nama>
	<kelas>2A</kelas>
	<jurusan>Teknik Informatika</jurusan>
	<biayasemester>7000000</biayasemester>
	<kodekelas>1</kodekelas>
	<asaldaerah>Lumajang</asaldaerah>
</mahasiswa>
<mahasiswa>
	<npm>115401</npm>
	<nama>Kezia</nama>
	<kelas>2B</kelas>
	<jurusan>Teknik Informatika</jurusan>
	<biayasemester>7000000</biayasemester>
	<kodekelas>2</kodekelas>
	<asaldaerah>NTT</asaldaerah>
</mahasiswa>
<mahasiswa>
	<npm>115402</npm>
	<nama>Maudy</nama>
	<kelas>2A</kelas>
	<jurusan>Tekik Informatika</jurusan>
	<biayasemester>7000000</biayasemester>
	<kodekelas>1</kodekelas>
	<asaldaerah>Jambi</asaldaerah>
</mahasiswa>
<mahasiswa>
	<npm>115403</npm>
	<nama>Ajrina</nama>
	<kelas>2B</kelas>
	<jurusan>Teknik Informatika</jurusan>
	<biayasemester>7000000</biayasemester>
	<kodekelas>2</kodekelas>
	<asaldaerah>Makassar</asaldaerah>
</mahasiswa>
<mahasiswa>
	<npm>115404</npm>
	<nama>Ratu</nama>
	<kelas>2A</kelas>
	<jurusan>Teknik Informatika</jurusan>
	<biayasemester>7000000</biayasemester>
	<kodekelas>1</kodekelas>
	<asaldaerah>Bulukumba</asaldaerah>
</mahasiswa>
<mahasiswa>
	<npm>115405</npm>
	<nama>Dhea</nama>
	<kelas>2B</kelas>
	<jurusan>Teknik Informatika</jurusan>
	<biayasemester>7000000</biayasemester>
	<kodekelas>2</kodekelas>
	<asaldaerah>Sumedang</asaldaerah>
</mahasiswa>
</logfika>
